---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: zabbix-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  labels:
    app: zabbix-web
spec:
  selector:
    app: zabbix-web
  ports:
    - port: 80
      targetPort: default
      protocol: TCP
