---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana
  annotations:
    prometheus.io/scrape: true
    prometheus.io/port: 3000
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  spec:
    selector:
      - port: 80
        targetPort: default
