---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zabbix-pgsql-pv
  labels:
    type: local
    app: zabbix-pgsql
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-pgsql-pvc
  labels:
    app: zabbix-pgsql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
