---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: zabbix.{{ domain_name }}
      http:
        paths:
          - path: /
            backend:
              serviceName: zabbix-server
              servicePort: 80
