---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "node"
        static_configs:
          - targets: 
              - "8.8.8.8:9100"
