---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: prometheus
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - port: 80
      targetPort: default
      protocol: TCP
