---
- src: geerlingguy.firewall
  version: 2.5.0

- src: geerlingguy.docker
  version: 2.8.1

- name: lucastercas.kubernetes-master
  src: https://github.com/lucastercas/ansible-role-kubernetes-master
  version: origin/master

- name: lucastercas.kubernetes-worker
  src: https://github.com/lucastercas/ansible-role-kubernetes-worker
  version: origin/master

- name: lucastercas.kubernetes-loadbalancer
  src: https://github.com/lucastercas/ansible-role-kubernetes-loadbalancer.git
  version: origin/master
