---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: zabbix-server
spec:
  selector:
    matchLabels:
      app: zabbix-server
  replicas: 1
  template:
    metadata:
      name: zabbix-server
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql
          resources:
            limits:
              memory: 256M
              cpu: 500m
          environment:
            DB_SERVER_HOST: ""
            POSTGRES_USER: ""
            POSTGRES_PASSWORD: ""
          ports:
            - name: default
              containerPort: 10050
          volumeMounts:
            - name: config-volume
              mountPath: /etc/zabbix/zabbix/
      volumes:
        - name: config-volume
          configMap:
            name: zabbix-server-config
